import os
from flask import Flask, request
from twilio.twiml.messaging_response import MessagingResponse
from twilio.rest import Client

app = Flask(__name__)

# Konfigurasi Twilio
account_sid = 'ACeefb17cb7a7f55d21b6a807bd5ab1a5b'
auth_token = '8c2c2a9d984c08706a09aaff7b57a867'
client = Client(account_sid, auth_token)

@app.route("/")
def home():
    return "Selamat datang di aplikasi Flask!"

@app.route("/webhook", methods=["POST"])
def webhook():
    incoming_msg = request.values.get("Body", "").lower()
    response = ""

    if incoming_msg ==  "halo":
        response = "Halo! Silakan pilih yang ingin kamu ketahui:\n1. Wisata (code : wst) \n2. Hotel (code : htl) \n3. Oleh-Oleh Khas (code : ook) "

    elif incoming_msg == "wst":
        response = "Anda memilih Wisata. Silakan pilih jenis wisata yang ingin kamu ketahui\n1. Wisata Alam (code : wa) \n2. Wisata Religi(code : wr) \n3. Wisata Buatan (code : wb) " 
    
    elif incoming_msg == "wa":
        response = "Anda memilih Wisata Alam. Silakan pilih opsi berikutnya:\n1. Grama Tirta Jatiluhur (code : gtj) \n2. Desa Wisata Kampung Tajur(code : dwkt) \n3. Gunung Parang(code : gp) \n4. Gunung Bangkok(code : gb) \n5. Waduk Cirata(code : wc)\n6. Situ Wanayasa(code : sw)  \n7. Curug Cipurut (code : cct)  \n8. Ujung Aspal - Pasirmuncang(code : uap)  \n9. Curug Cimata Indung (code : cci) \n10. Panarawangan Bukit Cinta (code : pbc)  \n11. Parang Gombong (code : pg)  \n12. Gunung Lembu (code : gl) \n13. Leuwi Cidomas (code : lc)  \n14. Kampung Sadang(code : ks)  \n15. Curug Tilu (code : ct)  \n16. Kampung Kahuripan (code : kk)  \n17. Alam Sari Wates (code : asw)  \n18. Ngaprak River Adventure (code : nra)  \n19. Saung Manglid (code : sm)  \n20. Taman Batu Mata Air Cijanun (code : tbmac)  \n21. Sasak Panyawangan (code : sp)  \n22. Skylodge Padjajaran Anyar (code : spa)  \n23. Hidden Valley Hills (code : hvh)  \n24. Bungursari Lake Park (code : blp)  \n25. Gunung Cupu(code : gc) " 
    elif incoming_msg == "gtj":
        response = "Anda memilih Grama Tirta Jatiluhur \n Deskripsi Wisata :\n Grama Tirta Jatiluhur merupakan kawasan yang menyajikan wisata serba air dari berperahu, selancar, kolam renang, hotel/penginapan, outbond, berkemah, hingga wisata kuliner. Dalam wilayah wisata Grama Tirta Jatiluhur, waduk jatiluhur berada. \n\n Lokasi Wisata :\nhttps://goo.gl/maps/goADwYNqPqs36XAw9 \n\n HTM :  \n harga tiket masuk Grama Tirta Jatiluhur adalah Rp27,500.00. Sementara saat weekend, harga tiket masuk Grama Tirta Jatiluhur adalah Rp30,000.00 \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 17.00 \n\n Kontak \n (0264) 201087 \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "dwkt":
        response = "Anda memilih Desa Wisata Kampung Tajur \n\n Deskripsi Wisata :\n Kampung Tajur dijadikan sebagai kampung wisata oleh Pemerintah Kabupaten Purwakarta. dirintis antara tahun 2002-2003, dan diresmikan sebagai kampung wisata dengan mencirikan dan menonjolkan adat istiadat dan kearifan lokal pada tahun 2004. jauh sebelum dijadikan Kampung wisata dan dikenal banyak orang dengan kampung yang mempertahankan adat kesundaan dan kearifan lokalnya, Kampung Tajur ternyata sudah ada sejak lama. bahkan ratusan tahun silam. \n\n Lokasi Wisata :\n https://goo.gl/maps/rYFpsvmVGzHvruJb9 \n\n HTM :  \n tiket masuk dan menginap 6-8 orang 250.000/orang ; biaya makan 17.000-25.000/porsi \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Kontak \n 087778614788 \n\n Alternatif kontak \n https://www.instagram.com/nusaena.tajur/ \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "gp":
        response = "Anda memilih Gunung Parang \n\n Deskripsi Wisata :\n Gunung setinggi 963 m dengan 3 puncak batu vulkanis terjal yang populer di kalangan pemanjat tebing. \n\n Lokasi Wisata :\n https://goo.gl/maps/5AwdKQAER5u1W8fr9\n\n HTM :  \n Harga tiket (jalur biasa) 10.000/orang ; harga tiket jalur ferrata 100 meter 100.000/orang, 300 meter 150.000/orang, 750 meter 465.000/orang ; harga tiket jalur taraje berbentuk paket mulai dari 150.000-750.000 per orang \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Fasilitas \n Area parkir, toilet, warung makanan dan minuman, penyewaan alat, guide \n\n Kontak \n 087770851010 \n\n Alternatif kontak \n  https://www.instagram.com/parangviaferrata/?hl=id \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "gb":
        response = "Anda memilih Gunung Bangkok\n\n Deskripsi Wisata :\n Puncak berbatu dengan area berkemah & pemandangan luas ke danau & lembah berhutan dari puncak. \n\n Lokasi Wisata :\n https://goo.gl/maps/gYgpNC3Gw9peNzpX7 \n\n HTM :  \n Tiket masuk 12.000/orang ; parkir motor 5.000/motor ; parkir mobil 10.000/mobil ; sewa tenda atau saung 10.000 \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Fasilitas \n Area parkir luas, toilet dan kamar mandi, musholla beserta perlengkapan shalat, warung makan dan minuman, jasa pemandu wisata, gazebo, arena outbond \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "wc":
        response = "Anda memilih Waduk Cirata\n\n Deskripsi Wisata :\n  Bendungan besar untuk PLTA yang selesai tahun 1990-an ini populer untuk pemancingan air tawar & naik perahu.\n\n Lokasi Wisata :\n https://goo.gl/maps/Bo9PbenBKdf5zVPZ7 \n\n HTM :  \n harga tiket masuk Rp.3.000 untuk sepeda motor dan Rp.5.000 untuk mobil. \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Fasilitas \n Tempat parkir kendaraan wisata, Warung-warung wisata, Toilet, Spot Foto Instagenic, Wahana permainan air dan adventure, Mushola, Penginapan, Gazebo, Perahu wisata \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "sw":
        response = "Anda memilih Situ Wanayasa \n\n Deskripsi Wisata :\n Waduk buatan dan area rekreasi dengan kafe di tepi waduk dan penginapan standar, yang berlatar pegunungan. \n\n Lokasi Wisata :\n https://goo.gl/maps/BuyzT5BVBfX6TNeq8 \n\n HTM : \n Tiket Masuk Gratis ; Parkir Sepeda Motor Rp2.000/motor ; Parkir Mobil Rp5.000/mobil \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Fasilitas \n Area parkir, toilet, Mushola \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "cct":
        response = "Anda memilih Curug Cipurut \n\n Deskripsi Wisata :\n Curug Cipurut ini merupakan destinasi wisata alam yang berada di bawah kaki kaki Gunung Burangrang. Air di Curug ini sangat jernih dan bersih serta sangat asri karena berada ditengah hutan yang rindang. Wisata hits ini sering dijadikan tempat spot foto yang Instagramable, tempat kemah, kegiatan piknik bersama keluarga dan kegiatan outbond lainnya dapat Anda lakukan disini. \n\n Lokasi Wisata :\n https://goo.gl/maps/UVk9SFauV6Qgftms5 \n\n HTM :  \n Tiket Masuk Rp20.000 ; Parkir Sepeda Motor Rp1.000/motor ; Parkir Mobil Rp2.000/mobil \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 17.00 \n\n Fasilitas \n mushola, gazebo, area parkir kendaraan, area perkemahan, tempat sampah, pos penjagaan \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "uap":
        response = "Anda memilih Ujung Aspal - Pasirmuncang \n\n Deskripsi Wisata :\n Ujung Aspal Purwakarta adalah wisata alam yang populer, dan hits di kalangan masyarakat, sekaligus menjadi rumah besar bagi goa bersejarah, serta air terjun yang cantik di Purwakarta. \n\n Lokasi Wisata :\n https://goo.gl/maps/2UW8RQXFtXyZPNBx8 \n\n HTM :  \n Tiket Masuk Wisata Rp10.000 ; Tiket Camping Rp20.000 ; Tiket Masuk Jembatan Gantung Rp10.000 ; Sewa Hammock Rp20.000 \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Kontak \n https://www.instagram.com/ujungaspal_pasirmuncang/ \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "cci":
        response = "Anda memilih Curug Cimata Indung \n\n Deskripsi Wisata :\n Curug Cimata Indung di Kecamatan Sukasari, merupakan salah satu lokasi wisata yang menghadirkan aliran air terjun kecil yang indah di Kabupaten Purwakarta, Jawa Barat. Segarnya air pegunungan dan pemandangan alam, membuat para pengunjunganya terhipnotis sehingga betah berlama-lama menikmati keindahan Curug tersebut. Curug Cimata Indung atau dalam bahasa Indonesia curug air mata bunda ini, biasanya diminati wisatawan ketika musim panas.  Bukan hanya wisatawan lokal, para pelancong luar negeri juga tak jarang berkunjung ke sana. \n\n Lokasi Wisata :\n https://goo.gl/maps/3tf8LeyLYaLNhSyLA  \n\n HTM :  \n biaya masuk sukarela namun ada biaya parkir sebesar 5.000 \n\n Waktu Buka/Tutup : \n 07.00 - 17.00 WIB \n\n Kontak \n 087879777542 \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "pbc":
        response = "Anda memilih Panarawangan Bukit Cinta \n\n Deskripsi Wisata :\n Sesuai namanya, tempat wisata ini menyuguhkan suasana alam dari atas perbukitan yang didukung dengan beragam spot foto menarik sehingga bisa dibilang, konsep yang diusung adalah perpaduan antara wisata alam dengan sentuhan modern. Disana wisatawan tidak hanya bisa menikmati suasana alam saja, namun juga bisa hunting foto sepuasnya. \n\n Lokasi Wisata :\n https://goo.gl/maps/vyPBjBZ59BYtbVGb7  \n\n HTM :  \n 5.000/orang \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 21.00 \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "pg":
        response = "Anda memilih Parang Gombong \n\n Deskripsi Wisata :\n Parang Gombong Purwakarta merupakan area lahan luas berumput hijau dengan pemandangan danau. Tempat tersebut sangat sejuk dan alami. Area wisata akan terasa agak panas pada siang hari dan sejuk pada malam hari. Panoram alam tersebut juga dapat menjadi spot selfie yang instagramable. \n\n Lokasi Wisata :\n https://goo.gl/maps/nxqDAa1XxqZJHkTB8 \n\n HTM :  \n Tiket Masuk 10.000/orang ; parkir motor 5.000/motor ; parkir mobil 10.000/mobil \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Kontak \n https://www.instagram.com/paranggombong_pwk/ \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "gl":
        response = "Anda memilih Gunung Lembu \n\n Deskripsi Wisata :\n Gunung Lembu memiliki ketinggian 792 mdpl dengan jalur pendakian cukup menantang dan sebuah batu besar yang dijuluki dengan batu lembu sebagai puncaknya, dimana akan terlihat pemandangan waduk Jatiluhur yang berada persis di bawahnya. Saat petang, mulai terlihat kerlip lampu-lampu di Kota Purwakarta.  \n\n Lokasi Wisata :\n https://goo.gl/maps/hvhddVkArBAizf8R9 \n\n HTM :  \n Tiket Masuk 10.000/orang ; Tiket Parkir 5.000 \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "lc":
        response = "Anda memilih Leuwi Cidomas \n\n Deskripsi Wisata :\n Sebuah objek wisata alam yang menampilkan keindahan sungai. Bukan sembarang sungai di pedesaan, sungai yang satu ini memiliki pesona yang memikat banyak wisatawan. Salah satu pesonanya adalah warna airnya yang cantik, hijau kebiru-biruan. Suasana di sekitar sungai juga begitu damai dan asri. \n\n Lokasi Wisata :\n https://goo.gl/maps/GF6CTSkGrCjaU7sC6  \n\n HTM :  \n Gratis (Tapi Ada Biaya Parkir Seikhlasnya) \n\n Waktu Buka/Tutup : \n Tidak memiliki jam resmi namun disarankan datang saat cuaca cerah \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "ks":
        response = "Anda memilih Kampung Sadang \n\n Deskripsi Wisata :\n Kampoeng Sadang merupakan kawasan wisata alam yang cocok buat kegiatan gathering komunitas, outbond sekolah, dan juga kegiatan lainnya yang memerlukan lahan luas. Kampoeng Sadang pun sangat pas digunakan untuk aktivitas family gathering atau kids adventure \n\n Lokasi Wisata :\n https://goo.gl/maps/xuBxBeBpRoQjYbQaA  \n\n HTM :  \n 35.000/orang \n\n Waktu Buka/Tutup : \n setiap hari kecuali senin jam 09.00 - 16.00 \n\n Kontak \n (0264) 8306621 \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "ct":
        response = "Anda memilih Curug Tilu \n\n Deskripsi Wisata :\n Curug Purwakarta merupakan sebuah curug atau air terjun yang ada di Purwakarta, meskipun cukup tersembunyi curug ini tak pernah sepi dari pengunjung. Curug yang satu ini masih asri dan alami, hal tersebut ditandai dengan masih rindangnya pepohonan yang ada di sekitar curug. Udara sejuk diiringi angin sepoi-sepoi serta suara air yang mengalir, menjadi alunan musik alam yang menenangkan. Maka tak heran jika Curug Tilu selalu ramai dikunjungi wisatawan, apalagi di akhir pekan banyak keluarga yang mengajak anak-anak untuk menghabiskan waktu bersama. \n\n Lokasi Wisata :\n https://goo.gl/maps/GF9arVPWswHquHBi7 \n\n HTM :  \n Tiket masuk: Rp. 7.500 ; Parkir: Rp. 5.000 ; Sewa pelampung: Rp. 5.000 \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 16.00 \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "kk":
        response = "Anda memilih Kampung Kahuripan \n\n Deskripsi Wisata :\n Merupakan kawasan eduwisata pengenalan lingkungan dan budaya Sunda dengan fasilitas alat permainan khas Sunda, kesenian khas Sunda seperti Calung dan Angklung, hingga energi alternatif tenaga surya dan air. Terdapat juga spot taman bermain, saung-saung dan camping ground. \n\n Lokasi Wisata :\n https://goo.gl/maps/SZGYMvT9ZNQ8diKK6 \n\n HTM :  \n Tiket Masuk Weekday Rp18.000 ; Tiket Masuk Weekend Rp20.000 ; Tiket Masuk Kolam Renang Weekday Rp16.000 ; Tiket Masuk Kolam Renang Weekend Rp20.000 ; Harga Tiket Wahana Panahan Rp10.000 ; Outbound, Flying Fox, ATV, Soang-Soangan, Sepeda Layang, Sisingaan, Gerabah, Pertanian (Menangkap Ikan, Memandikan Kerbau) Rp20.000 \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 17.00 \n\n Fasilitas \n tempat parkir, toilet, musala, dan tempat cuci tangan. \n\n Kontak \n 0811164642 \n\n Alternatif kontak \n 087828474148 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "asw":
        response = "Anda memilih Alam Sari Wates \n\n Deskripsi Wisata :\n Alam Sari Wates Adventure adalah wisata Purwakarta yang menyajikan beragam wahana wisata, hingga penginapan, dalam satu kawasan yang sama. \n\n Lokasi Wisata :\n https://goo.gl/maps/p3h57jXmgcTk2a5c9 \n\n HTM :  \n Photobooth Rp15.000 ; Waterboom Rp15.000 ; Mini Motocross/ATV Rp15.000 ; Flying Fox Rp10.000 ; Flying Fox Extreme Rp15.000 ; Playground/Taman Rp15.000 ; Waterball/Ban Rp5.000 ; Airwalk Rp10.000 ; Mandi bola Rp5.000 ; Skyswing Rp10.000 ; Tong Gandeng Rp10.000 ; Sepatu Roda Rp10.000 ; Tiket Terusan Rp35.000 || Suite Room 225.000 (permalam weekday) 300.000 (permalam weekend) ; Deluxe Room 175.000 (permalam weekday) 200.000 (permalam weekend) ; Deluxe AC Room 175.000 (permalam weekday) 200.000 (permalam weekend) ;  Deluxe AC Room 175.000 (permalam weekday) 200.000 (permalam weekend) ; Standard Room 140.000 (permalam weekday) 160.000 (permalam weekend) ; Guest House 750.000 (permalam weekday) 1.000.000 (permalam weekend) ; Family Room 450.000 (permalam weekday) 550.000 (permalam weekend) \n\n Waktu Buka/Tutup : \n Penginapan Buka 24 Jam \n\n Fasilitas \n Area parkir, Toilet, Mushola, Restoran, atau cafe, Spot foto, Wahana permainan, Taman, Kolam renang. \n\n Kontak \n (0264) 620123 \n\n Alternatif kontak \n 0811465650 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "nra":
        response = "Anda memilih Ngaprak River Adventure  \n\n Deskripsi Wisata :\n Purwakarta memiliki surga tersembunyi bagi penikmat arum jeram, mengingat sensasinya dijamin sangat berbeda dan bisa bikin puas dan ketagihan. Wisata arum jeram ini bisa Anda temukan di Kampung Tanjaknangsi, Desa Raharja, Kecamatan Wanayasa, Kabupaten Purwakarta. Di tempat tersebut menawarkan sensasi susur sungai mengunakan ban dalam karet atau yang disebut dengan river tubing lewat pengelolaan wisata yang dikenal dengan nama Ngaprak River Adventure. BACA JUGA:  3 Destinasi Wisata di Pasuruan, Penasaran Nggak? Wisata arum jeram ini mengajak Anda menelusuri Sungai Ciherang sepanjang 5 kilometer dengan waktu tempuh selama 3 jam. \n\n Lokasi Wisata :\n https://goo.gl/maps/GpAKFirLihfNV2es6 \n\n HTM :  \n biaya sebesar Rp 120 ribu termasuk biaya makan dan dokumentasi serta angkutan mobil \n\n Waktu Buka/Tutup : \n setiap hari kecuali jumat jam 08.00 - 16.00 \n\n Kontak \n 081299260872 \n\n Alternatif kontak \n https://www.instagram.com/ngaprakriver/ \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "sm":
        response = "Anda memilih Saung Manglid \n\n Deskripsi Wisata :\n Saung Manglid ini merupakan sebuah kawasan agrowisata yang lengkap. Di dalamnya terdapat area kebun bunga berbagai jenis yang bisa Anda jadikan lokasi berfoto. Tidak hanya kebun atau taman bunga yang cantik, di berbagai area juga disediakan area yang memang digunakan khusus untuk berfoto. \n\n Lokasi Wisata :\n https://goo.gl/maps/9qd3Bvf5NFqSm5UG8 \n\n HTM :  \n 10.000/orang \n\n Waktu Buka/Tutup : \n setiap hari jam 09.00 - 21.00 \n\n Kontak \n 081211379491 \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tbmac":
        response = "Anda memilih Taman Batu Mata Air Cijanun \n\n Deskripsi Wisata :\n Taman yang berada di di Kecamatan Bojong ini cocok buat Anda yang hobi berenang tanpa campuran bahan kimia di airnya. Karena di kolam ini sumber airnya berasal dari mata air pegunungan. Mata air di sini sangat jernih. Kedalamannya 3 meter. Kolam tersebut dimanfaatkan untuk kebutuhan penduduk sekitar. Kolam itu berada di area hijau. Pepohonan menghiasi sekitarnya. \n\n Lokasi Wisata :\n https://goo.gl/maps/7Sg1XjHewupXStks7  \n\n HTM :  \n 20.000/orang \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 17.00 \n\n Kontak \n 0811820101 \n\n Alternatif kontak \n https://www.instagram.com/tamanbatu.pwk/ \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "sp":
        response = "Anda memilih Sasak Panyawangan \n\n Deskripsi Wisata :\n Sasak Panyawangan Purwakarta merupakan sebuah destinasi wisata alam yang menyuguhkan pemandangan gunung batu. Wisata ini terapit di antara dua gunung batu dan dekat dengan bendungan yang legendaris, yakni Bendungan Jatiluhur. Ada beberapa wahana menarik yang bisa wisatawan explore di tempat ini. \n\n Lokasi Wisata :\n https://goo.gl/maps/XghbD3MUyr1vrf2N7 \n\n HTM :  \n 10.000/orang \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 16.00 \n\n Fasilitas \n Tempat parkir kendaraan wisatawan cukup luas, Pusat Informasi dan loket destinasi, Toilet umum, Mushola, Spot foto instagenic, Kolam renang, Gazebo, Wahana permainan seru, Camping ground, Outbond arena, Penginapan, Warung wisata \n\n Kontak \n12 081388078484 \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "spa":
        response = "Anda memilih Skylodge Padjajaran Anyar\n\n Deskripsi Wisata :\n Skylodge Padjajaran Anyar merupakan hotel gantung pertama di Indonesia yang disebut-sebut menyaingi hotel gantung di Peru yang terkenal. Bebeda dengan hotel lain yang dibangun di atas tanah, Skylodge Padjajaran Anyar berada 500 mdpl di atas tebing bebatuan Gunung Parang. \n\n Lokasi Wisata :\n https://goo.gl/maps/JiJGADJJqwpEEPs59 \n\n HTM :  \n Rp. 3.000.000 hingga Rp. 5.000.000/malam \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Fasilitas \n 4 buah tempat tidur, toilet portable, listrik,  AC, TV, meja makan, wastafel, oven, handy talkie untuk berkomunikasi, tirai untuk penutup dinding kamar  hingga balkon dengan view Bendungan Jatiluhur. \n\n Kontak \n12 087874708230 \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "hvh":
        response = "Anda memilih Grama Tirta Jatiluhur \n\n Deskripsi Wisata :\n Hidden Valley Hills adalah negeri dongeng di atas awan yang tercipta dari inspirasi ditemukannya tugu peninggalan zaman Belanda Anno 1898M di lokasi ini, yang terkait erat dengan G. Cupu dengan ketinggian yang sama 362 mdpl. \n\n Lokasi Wisata :\n https://goo.gl/maps/jaSb2WNpJ8z4hr64A \n\n HTM :  \n HTM Hidden Valley Hills Purwakarta sebesar Rp 35.000 per orang dan jika anda ingin renang akan dikenakan tarif sebesar Rp 25.000 per orang. \n\n Waktu Buka/Tutup : \n Setiap hari jam 08.00 - 19.00 \n\n Fasilitas \n Resort, Outdoor Event, Meeting Room dan juga terdapat Kolam Renang  \n\n Kontak \n12 085959672424 \n\n Alternatif kontak \n https://www.hiddenvalleyhills.com/ \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "blp":
        response = "Anda memilih Bungursari Lake Park \n\n Deskripsi Wisata :\n Bungursari Lake Park ini merupakan destinasi wisata alam yang juga menawarkan sisi edukasi pada para pengunjungnya. Di destinasi ini, pengunjung akan disuguhkan dengan pesona pemandangan danau. \n\n Lokasi Wisata :\n https://goo.gl/maps/8tuThxYGLrTCnncQ8 \n\n HTM :  \n HTM 15.000/orang (weekday) ; 20.000/orang (weekend) \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 19.00 \n\n Fasilitas \n Area parkir, toilet, spot foto, wahana perahu, wisata budaya, cafe & resto \n\n Kontak \n12 085889372022 \n\n Alternatif kontak \n http://bungursarilakepark.com/ \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "gc":
        response = "Anda memilih Gunung Cupu \n\n Deskripsi Wisata :\n Gunung Cupu adalah salah satu gunung yang tergolong sangat unik di Indonesia. Jika ingin mendaki gunung ini akan berhadapan dengan bebatuan. \n\n Lokasi Wisata :\n https://goo.gl/maps/UhrLFRNou5KgkqFA8 \n\n HTM :  \n Gratis ; 2.000/motor ; 5.000/mobil \n\n Waktu Buka/Tutup : \n Setiap hari 24 jam \n\n Kontak \n 087725139681 \n\n Alternatif kontak \n  \n\n Selamat liburan, hati-hati di jalan." 

        
    elif incoming_msg == "wr":
        response = "Anda memilih Wisata Religi. Silakan pilih opsi berikutnya:\n1. Makam Syech Ba'ing Yusuf (code : msby) \n2. Makam Mama Sempur (code : mms)  \n3. Makam Eyang Pandita Tajur & Sekitarnya (code : mept)  \n4. Makam Eyang Gandasoli (code : meg). " 
    elif incoming_msg == "msby":
        response = "Anda memilih Makam Syech Ba'ing Yusuf \n\n Deskripsi Wisata :\n Makam Syech Baing Yusuf berlokasi di pusat kota, tepatnya di belakang Masjid Agung Baing Yusuf Purwakarta. Berdasarkan cerita berkembang, Syech Baing Yusuf merupakan salah satu tokoh sejarah yang menyebarkan Islam di Purwakarta. Beliau merupakan guru Syech Nawawi Al Bantani ulama Indonesia yang menjadi Imam di Masjidil Haram. \n\n Lokasi Wisata :\n https://goo.gl/maps/gg4kUMTavUtMoT3w5 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n  setiap hari 24 jam \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat berziarah, hati-hati di jalan." 
    elif incoming_msg == "mms":
        response = "Anda memilih Makam Mama Sempur\n\n Deskripsi Wisata :\n Makam Mama Sempur berlokasi di Desa Sempur, Kecamatan Plered. Nama lengkapnya adalah KH Tubagus Ahmad Bakri bin KH Tubagus Syeda bin KH Tubagus Arsyad. Mama Sempur adalah salah satu tokoh muslim di Purwakarta yang menyebarkan agama Islam. Beliau saat ini dikenal sebagai Mama Sempur. Dia mendapat garis layak dari Keraton Banten (Istana Banten), diambil dari garis layak KH Tubagus Arsyad dari Keraton Banten. Di akhir setiap Dzulqaidah (11 bulan tahun Hijriah), di tempat itu selalu diadakan Haulan, sebuah peristiwa untuk mengingat wafatnya Mama Sempur. \n\n Lokasi Wisata :\n https://goo.gl/maps/odzmWtxeaf4xscZs8 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n  setiap hari 24 jam \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat berziarah, hati-hati di jalan." 
    elif incoming_msg == "mept":
        response = "Anda memilih Makam Eyang Pandita Tajur & Sekitarnya \n\n Deskripsi Wisata :\n Oleh masyarakat setempat Eyang Pandita dipercaya sebagai sesepuh Desa Pasanggrahan. Keunikan dari makam ini adalah lokasinya yang berada di atas bukit, sehingga dapat terlihat pemandangan gunung Burangrang, area pesawahan, perkebunan sayur warga, dan kawasan hutan.  \n\n Lokasi Wisata :\n https://goo.gl/maps/iVe5jrfPX8mZNU8C6 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n  setiap hari 24 jam \n\n Kontak \n 083149397123 \n\n Alternatif kontak \n - \n\n Selamat berziarah, hati-hati di jalan." 
    elif incoming_msg == "meg":
        response = "Anda memilih Makam Eyang Gandasoli \n\n Deskripsi Wisata :\n Semasa hidupnya, Eyang Dalem Gandasoli ini merupakan penyebar agama Islam di daerah Purwakarta yang singgah di Gandasoli. Desa tersebut saat ini masuk ke wilayah Kecamatan Plered. Maka tak heran jika banyak masyarakat menyempatkan untuk berziarah ke sini.. \n\n Lokasi Wisata :\n https://goo.gl/maps/CivsbohtTAEsGF5V9 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n  setiap hari 24 jam \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat berziarah, hati-hati di jalan." 

    elif incoming_msg == "wb":
        response = "Anda memilih Wisata Buatan. Silakan pilih opsi berikutnya:\n1. Taman Sribaduga (code : ts) \n2. Taman Surawisesa (code : tsw) \n3. Taman Pancawarna (code : tpw ) \n4. Taman Pasanggrahan Pajajaran (code : tpp)  \n5. Taman Maya Datar (code : tmd)  \n6. Bale Panyawangan Diorama Nusantara (code : bpdn) \n7 Workshop Litbang Keramik (code : wlk) \n8. Kolam Renang Giri Tirta (code : krgt ) \n9. Kolam Renang Cihanjawar (code : krc) \n10. Kolam Tjek Tse Long (code : kttl) \n11. Jaya Tirta Abadi Waterboom (code : jtaw) \n12. Bale Indung Rahayu (code : bir) \n13. Galeri Wayang (code : gw) \n14. Kuya Maranggi Waterpark (code : kmw) \n15. Taman Pancaniti (code : tpi) \n16. Taman Parcom (code : tpm) \n17. Taman Citra Resmi (code : tcr) \n18. Taman Pembaharuan (code : tp) \n19. Green Valley Water Park (code : gvwp) \n20. Kolam Renang Cisabuk (code : krc) \n21. Kolam Renang Tajur Indah (code : krti) \n22. Castle Lampion (code : cl) \n23. Cikao Park (code : cp) \n24. Tirta Kahuripan Wanayasa (code : tkw) \n25. Kolam Renang Ciloa (code : krca) \n26. Batu Apung Alam Hijau (code : baah) \n27.  Kolam Renang Pusaka Water Park (code : krpwp) \n28. Kolam Renang Babakan Jati (code : krbj)." 
    elif incoming_msg == "ts":
        response = "Anda memilih Taman Sribaduga \n\n Deskripsi Wisata :\n Taman Air Mancur Sri Baduga adalah sebuah destinasi liburan yang lokasinya berada di Alun-Alun Purwakarta, Jawa Barat. Obyek wisata ini menyajikan atraksi air menari yang dilengkap dengan lampu warna warni yang cantik dan memukau. \n\n Lokasi Wisata :\n https://goo.gl/maps/ctuHLjE6tCY6o1at5 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n Area Sekitar Taman Dibuka. Namun untuk pertunjukan Air Mancur jadwalnya tidak menentu karena masalah debit air yang turun. \n\n Fasilitas \n Tempat parkir kendaraan, Toilet, Mushola, Warung makan, Gazebo, Tempat duduk wisata \n\n Kontak \n12  \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tsw":
        response = "Anda memilih Taman Surawisesa \n\n Deskripsi Wisata :\n Taman edukasi untuk anak-anak dengan berbagai fasilitas, seperti layar besar berisi film edukatif bertema sosial, teropong bintang hingga air mancur mini. Dihadirkan pula permainan tradisional seperti egrang, songlah, congklak, lompat tali, panggal (gasing dari kayu), kelerang dan lainnya. \n\n Lokasi Wisata :\n https://goo.gl/maps/G3LrER9jD9oaP6dL7 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n  Jumat (Malam Sabtu) \n\n Fasilitas \n Layar besar berisi film edukatif bertema sosial, teropong bintang hingga air mancur mini. \n\n Kontak \n12 - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tpw":
        response = "Anda memilih Taman Pancawarna \n\n Deskripsi Wisata :\n Obyek Wisata Taman Pancawarna di Purwakarta Jawa Barat sangat cocok untuk mengisi kegiatan liburan anda, apalagi saat liburan panjang seperti libur nasional, ataupun hari ibur lainnya. Keindahan Obyek Wisata Taman Pancawarna di Purwakarta Jawa Barat ini sangatlah baik bagi anda semua yang berada di dekat atau di kejauhan untuk merapat mengunjungi tempat Obyek Wisata Taman Pancawarna di Purwakarta Jawa Barat di kota purwakarta. \n\n Lokasi Wisata :\n https://goo.gl/maps/c3Q9eZVa9UHiQX3H9 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n  08.00 - 18.00 WIB \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tpp":
        response = "Anda memilih Taman Pasanggrahan Pajajaran\n\n Deskripsi Wisata :\n Taman Pasanggrahan Padjajaran memiliki nuansa etnik kesundaan dan modern, sehingga menjadi daya tarik tersendiri bagi wisatawan yang datang ke Purwakarta \n\n Lokasi Wisata :\n https://goo.gl/maps/T7ucAgwDyg9WSZzB6 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n 06.00 - 18.00 WIB \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tmd":
        response = "Anda memilih Taman Maya Datar \n\n Deskripsi Wisata :\n Taman Maya Datar, dan Pancawarna dibangun pada masa Bupati Dedi Mulyadi, sebagai sosok yang mampu menjadikan wisata Purwakarta, tidak kalah saing dengan wisata di kota lain yang sudah lebih dulu populer di masyarakat. Setiap tempat wisata di Purwakarta, disajikan secara epik. Dari mulai ornamen, tata letak, arsitektur, nilai filosofis, hingga nilai budaya, mampu tersaji indah dalam keseruan wisata. Termasuk di Taman Maya Datar, dan Taman Pancawarna Purwakarta. \n\n Lokasi Wisata :\n https://goo.gl/maps/mLRdYZ54wVKzSxEc9 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n  15.00 - 18.00 WIB \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "bpdn":
        response = "Anda memilih Bale Panyawangan Diorama Nusantara \n\n Deskripsi Wisata :\n  Bale Panyawangan Diorama Nusantara merupana ungkapan awal peradaban manusia di Indonesia dan perkembangannya dari masa ke masa sampai sekarang yang ditinjau dari berbagai aspek seperti aspek wilayah, keagamaan, kesenian, sosial, budaya, politik, ekonomi, sistem pemerintahan, hingga kepada infrastruktur yang ditampilkan melalui perpaduan arsip, seni dan teknologi adalah untuk memperkenalkan arsip kepada masyarakat dengan cara yang mudah dipahami dan menarik. \n\n Lokasi Wisata :\n https://goo.gl/maps/6cxaejTEWTfr1BF16 \n\n HTM :  \n Dewasa : 5.000/orang ; Anak-anak : 3.000/orang \n\n Waktu Buka/Tutup : \n Setiap hari kecuali Senin, Sabtu dan Minggu ada 2 sesi 09.00 - 12.00 dan 13.00 - 15.00 \n\n Fasilitas \n Toilet, Parkir Luas, Tempat Duduk, Tim Pemandu. \n\n Kontak \n12 087710515051 \n\n Alternatif kontak \n https://www.instagram.com/balepanyawangandiorama/  \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "wlk":
        response = "Anda memilih Workshop Litbang Keramik  \n\n Deskripsi Wisata :\n Merupakan pusat kerajinan keramik dan tembikar yang sudah ada sejak tahun 1900an. Hasil kerajinannya pun variatif; dari celengan ayam kecil hingga vas berukuran besar. Uniknya, bukan hanya sekadar membeli hiasan keramik dan tembikar, kita pun bisa mencoba langsung membuat keramik dengan proses yang masih tradisional di UPTD Litbang Keramik Plered Purwakarta. \n\n Lokasi Wisata :\n https://goo.gl/maps/1az31Hupgk72ivmj9  \n\n HTM :  Hubungi Pihak Terkait \n  \n\n Waktu Buka/Tutup : \n Senin - Jumat 08.00 - 16.00 WIB \n\n Kontak \n 087779830642 \n\n Alternatif kontak \n 087779694857 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "krgt":
        response = "Anda memilih Kolam Renang Giri Tirta \n\n Deskripsi Wisata :\n Kolam renang ini berada di ketinggian 500 mdpl. Tempat yang menghadirkan kesejukan dan keteduhan ini memang sangat menyenangkan untuk dikunjungi. Selain memiliki udara yang sejuk, air yang dingin juga sangat menyegarkan apalagi datang ketempat ini saat siang hari dimana panas terik matahari masih sangat terasa \n\n Lokasi Wisata :\n https://goo.gl/maps/7rwcQc5qKGmG7pLH7 \n\n HTM :  \n Weekday: Rp40.000 ; Weekend: Rp50.000 \n\n Waktu Buka/Tutup : \n Senin - Jumat 08.00 - 17.00 WIB \n\n Kontak \n (0264) 8641414 \n\n Alternatif kontak \n  \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "krc":
        response = "Anda memilih Kolam Renang Cihanjawar  \n\n Deskripsi Wisata :\n Kolam renang ini memiliki air yang sangat dingin karena berasal dari gunung Burangrang. Udara yang segar dengan panorama aliran sungai dan pesawahan di sekitar kolam renang menjadi daya tarik sendiri. \n\n Lokasi Wisata :\n https://goo.gl/maps/aLxfTA1YYLVeNgEQ6 \n\n HTM :  \n Weekday: Rp20.000 ; Weekend: Rp25.000 \n\n Waktu Buka/Tutup : \n 07.00 - 17.00 WIB \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "kttl":
        response = "Anda memilih Kolam Tjek Tse Long \n\n Deskripsi Wisata :\n Kolam Renang Cek Tse Long adalah kolam renang yang cocok untuk keluarga, banyak lesehan tempat untuk makan-makan selagi anda menunggu anak berenang, bila anda berkunjung ke wanayasa mari mampir kesini \n\n Lokasi Wisata :\n https://goo.gl/maps/sRifGh6nAEp7EumRA \n\n HTM :  \n Sabtu Minggu untuk dewasa 25.000, anak 20.000, untuk hari Senin - Kamis semua 20.000 \n\n Waktu Buka/Tutup : \n setiap hari kecuali jumat jam 08.00 - 16.00 \n\n Fasilitas \n 4 kolam renang 2 untuk anak-anak dan 2 untuk dewasa. \n\n Kontak \n12 087714638156 \n\n Alternatif kontak \n https://www.instagram.com/cektselong/  \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "jtaw":
        response = "Anda memilih Jaya Tirta Abadi Waterboom \n\n Deskripsi Wisata :\n Destinasi Wisata Kolam Renang  dan Water Boom (JTA), Udaranya sangat sejuk, ciri khas udara pegunungan sangat terasa, menawarkan wisata wahana air dengan berbagai fasilitas untuk liburan keluarga. Fasilitas yang di tawarkan antara lain kolam renang untuk dewasa dan kolam renang untuk anak, water boom, ember tumpah, Seluncuran, Permainan anak, Arena ketangkasan (Game zone),Roller Coaster Mini. \n\n Lokasi Wisata :\n https://goo.gl/maps/GKkMpw5TdkeWmvRf9 \n\n HTM :  \n  Hari Senin s.d Juma Rp 25.000 per orang ; Hari Sabtu s.d Minggu Rp 30.000 per orang ; Hari  libur nasional Rp 30.000 per orang \n\n Waktu Buka/Tutup : \n Weekday: 08.00-16.00 WIB ; Weekend: 07.00-16.00 WIB \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "bir":
        response = "Anda memilih Bale Indung Rahayu  \n\n Deskripsi Wisata :\n Bale Indung Rahayu yang berarti Tempat Kemuliaan Ibu bertutur tentang proses kelahiran manusia dan peran seorang ibu dalam merawat anak-anaknya dengan sentuhan budaya sunda. Kehidupan dan perjalanan hidup manusia di alam sunda ditampilkan secara apik melalui seni relief, lukisan, pahat, dan bangunan. \n\n Lokasi Wisata :\n https://goo.gl/maps/kBM5dqLeBJ8A1umV9  \n\n HTM :  \n  Rp5.000 untuk dewasa dan Rp3.000 untuk anak-anak  \n\n Waktu Buka/Tutup : \n setiap hari kecuali senin jam 08.00 - 15.00 \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "gw":
        response = "Anda memilih Galeri Wayang  \n\n Deskripsi Wisata :\n Para pengunjung yang berada di Galeri Wayang bisa mendapatkan berbagai informasi mengenai sejarah wayang nusantara. Suasana belajar akan semakin menyenangkan karena galeri ini memiliki pencahayaan yang tenang dan penataan ruang yang menarik. Warna hitam dan putih menghiasi setiap ruangan di Galeri Wayang. Setiap ruangan maupun sudutnya juga bisa dijadikan lokasi spot foto yang Instagramable. Terdapat dua ruangan di galeri ini. Pada ruangan pertama dihiasi oleh dua dinding berhiaskan relief kisah utama Mahabharata dan Ramayana. \n\n Lokasi Wisata :\n https://goo.gl/maps/LK7ZFygUaJhHL2cJ8  \n\n HTM :  \n Rp5 ribu untuk kategori dewasa ; kategori anak di bawah usia 6 tahun dibanderol Rp3 ribu. \n\n Waktu Buka/Tutup : \n setiap hari kecuali senin jam 08.00 - 16.00 \n\n Kontak \n 085798650991 \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "kmw":
        response = "Anda memilih Kuya Maranggi Waterpark r \n\n Deskripsi Wisata :\n Kuya Maranggi Waterpark merupakan salah satu kolam renang modern yang ada di Purwakarta. Namanya unik ya, diambil dari salah satu jenis hewan. Yakni kuya, kalau dalam bahasa Indonesia biasa disebut kura-kura. Penyematan kuya, pada waterpark yang baru berdiri tahun 2017 lalu ini bukan tanpa alasan. Disamping memiliki kolam renang yang bentuknya menyerupai kura-kura, kamu dapat menjumpai hewan tersebut juga loh di sini. \n\n Lokasi Wisata :\n https://goo.gl/maps/8eu6E48E1PFVHGFH8  \n\n HTM :  \n Harga tiket Rp. 50.000 (weekdays) dan Rp. 75.000 (weekend) \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 17.00 \n\n Kontak \n 085173335353 \n\n Alternatif kontak \n 087726559515 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tpi":
        response = "Anda memilih Taman Pancaniti \n\n Deskripsi Wisata :\n Merupakan salah satu taman yang berada di Kabupaten Purwakarta. Di taman ini terdapat pajangan alat musik berupa kecapi. \n\n Lokasi Wisata :\n https://goo.gl/maps/fRohvH1HXnzFJ7tq7 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n setiap hari 24 jam \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tpm":
        response = "Anda memilih Taman Parcom \n\n Deskripsi Wisata :\n Merupakan salah satu taman yang berada di Kabupaten Purwakarta. Taman ini sering dimanfaatkan oleh warga Kabupaten Purwakarta untuk olahraga seperti lari pagi dan sore, hingga bersantai. Taman Parcom juga menjadi tempat berkumpul dan refreshing, telebih taman kota ini di desain dengan baik, terawat, penuh dengan tumbuhan (pohon dan taman bunga), serta minimalis dilengkapi tempat duduk-duduk. \n\n Lokasi Wisata :\n https://goo.gl/maps/XNA5W9rwqmHoRLQj7 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n setiap hari jam 07.00 - 10.00 \n\n Kontak \n (0264) 215462 \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tcr":
        response = "Anda memilih Taman Citra Resmi \n\n Deskripsi Wisata :\n Taman Citra Resmi dibangun sebagai penanda perjuangan wanita Sunda, juga patung badak putih sebagai simbol Situ Buled Purwakarta. Dikelilingi oleh cantiknya bunga-bunga. Taman ini menjadi pilihan tepat untuk ber-selfie ria tatkala berkunjung ke Purwakarta. \n\n Lokasi Wisata :\n https://goo.gl/maps/CrcHwhov8bsxsaL29 \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n Setiap hari 24 jam  \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tp":
        response = "Anda memilih Taman Pembaharuan \n\n Deskripsi Wisata :\n Taman Pembaharuan dirancang dengan menerapkan semangat kepahlawanan dan unsur edukasi dengan dibangunnya patung tokoh - tokoh nasional, seperti Soekarno, Bung Hatta, serta Abdurrahman Wahid (Gus Dur). \n\n Lokasi Wisata :\n https://goo.gl/maps/AUXyd6fTv9LBwDwC9  \n\n HTM :  \n Gratis \n\n Waktu Buka/Tutup : \n senin-rabu 08.30 - 16.30, kamis-jumat 24 jam dan sabtu-minggu tutup \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "gvwp":
        response = "Anda memilih Green Valley Water Park \n\n Deskripsi Wisata :\n Taman rindang dengan kolam renang, seluncuran air & kolam arus, plus patung binatang & mobil vintage. \n\n Lokasi Wisata :\n https://goo.gl/maps/HcfzZcqmWjMxM11v8 \n\n HTM :  \n 40.000/ orang \n\n Waktu Buka/Tutup : \n setiap hari kecuali jumat jam 09.00 - 17.00 \n\n Fasilitas \n Lazy river, kolam renang waterboom dengan water slide spiral yang tinggi dan panjang, museum transportasi, taman alutsista TNI, kapal pesiar, wahana, bale dan resto. \n\n Kontak \n12 (0264)8307204 \n\n Alternatif kontak \n https://www.instagram.com/greenvalleywaterpark/?hl=id \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "krc":
        response = "Anda memilih Kolam Renang Cisabuk \n\n Deskripsi Wisata :\n Kolam renang di Purwakarta ini tidak jauh dari perkotaan. Anda juga dapat mengajak si kecil atau anggota keluarga yang lain untuk berenang di Kolam Renang Cisabuk. Di kolam renang tersebut terdapat beberapa tipe kolam renang, baik untuk para pengunjung yang telah mahir berenang maupun yang masih dalam tahap belajar. Fasilitas seperti toilet, arena bermain, dan kamar bilas yang bersih juga ditawarkan oleh Kolam Renang Cisabuk ini. \n\n Lokasi Wisata :\n https://goo.gl/maps/wrgQPq1pXdFFjjYs6 \n\n HTM :  \n 15.000/orang \n\n Waktu Buka/Tutup : \n setiap hari kecuali jumat jam 08.00 - 16.00 \n\n Kontak \n - \n\n Alternatif kontak \n - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "krti":
        response = "Anda memilih Kolam Renang Tajur Indah \n\n Deskripsi Wisata :\n Kolam renang Tajur Indah parakan lima purwakarta merupakan wisata swimming pool keluarga yang recommended. Swimming pool ini tidak terlalu besar dan tidak terlalu kecil, atau bisa dikatakan cukup, namun dengan fasilitas yang cukup kumplit semua ada di sana. \n\n Lokasi Wisata :\n https://goo.gl/maps/oRskepRoSA7GNDqc8 \n\n HTM :  \n Rp20.000 pada hari biasa dan weekend Rp25.000 \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 17.00 \n\n Fasilitas \n10 Kantin, WC, Mushola, Ruang ganti, Tempat bilas. \n\n Kontak \n12 (0264) 8308123 \n\n Alternatif kontak \n http://www.instagram.com/tajurindah_ofc/  \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "cl":
        response = "Anda memilih Castle Lampion \n\n Deskripsi Wisata :\n Setiap sudut kastil dapat dijadikan spot foto yang Instagramable, karena arsitektur serta sentuhan seni dan tata letaknya yang indah. Selain itu, berdiri di dataran lebih tinggi, sehingga pemandangan alam, pemukiman dan kawasan Cikao menjadi suguhan. \n\n Lokasi Wisata :\n https://goo.gl/maps/aKpLMD5Byaz5oTpL9 \n\n HTM :  \n Tiket Masuk Dewasa 20.000, Anak 15.000 ; Parkir 3.000/motor, 5.000/mobil \n\n Waktu Buka/Tutup : \n senin-jumat jam 12.00 - 22.00 dan sabtu - minggu 10.00 - 22.00 \n\n Fasilitas \n mushola, wifi, toilet, tempat parkir, area bermain. \n\n Kontak \n12 081779585151 \n\n Alternatif kontak \n14 - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "cp":
        response = "Anda memilih Cikao Park  \n\n Deskripsi Wisata :\n Cikao Park adalah taman wisata yang terdiri dari berbagai macam wahana. Salah satu yang paling populer dari tempat ini yaitu kolam renangnya. Ada kolam renang yang bisa dinikmati oleh semua usia yaitu kolam utama yang berada di area waterpark. Kolamnya sangat luas, seperti pantai yang mengelilingi sebuah pulau \n\n Lokasi Wisata :\n https://goo.gl/maps/KA43tDF3dubkjVcc8 \n\n HTM :  \n Wisata/utama & taman bunga Rp20.000 ; HTM Waterpark (Weekday: Rp30.000 ; Weekend: Rp50.000) \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 17.00 \n\n Fasilitas \n Waterboom, taman satwa dan dino park, arena bermain, taman lampion hingga rumah ilusi. \n\n Kontak \n12 08111239933 \n\n Alternatif kontak \n14 - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tkw":
        response = "Anda memilih Tirta Kahuripan Wanayasa \n\n Deskripsi Wisata :\n Kahuripan Tirta Wanayasa (KTW) Merupakan Wahana Rekreasi Air yang dibangun dengan konsep Natural Modern. Nuansa keindahan dari tempat ini menonjolkan segi kemurnian alam baik dari struktur maupun tata letak setiap arena. Wahana Rekreasi Air ini lokasinya persis di samping selatan Situ Wanayasa, sehingga bagi anda yang ingin rekreasi ke daerah Wanayasa bisa Sekaligus mengunjungi Wahana Rekreasi Air Kahuripan Tirta Wanayasa sambil menikmati keindahan Situ Wanayasa. \n\n Lokasi Wisata :\n https://goo.gl/maps/czK8z9FZajTrj3Nt8 \n\n HTM :  \n Harga Tiket Masuk: Rp40.000 (Weekday) - Rp50.000 (Weekend) \n\n Waktu Buka/Tutup : \n Setiap hari jam 08.00 - 18.00 \n\n Fasilitas \n Tempat parkir kendaraan wisata, Kamar mandi, Mushola, Restoran, Playground, Kebun buah, Kolam renang, Kebun binatang mini, Penginapan. \n\n Kontak \n12 081286445844 \n\n Alternatif kontak \n14 - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "krca":
        response = "Anda memilih Kolam Renang Ciloa \n\n Deskripsi Wisata :\n Wisata alam Ciloa Park dengan pesona alam yang berlokasi di Desa Gardu Kecamatan Kiarapedes, Kabupaten Purwakarta, Jawa Barat yang mampu menyajikan wisata air yang cukup menarik dengan daya tarik sumber air langsung dari mata air yang menghasilkan debit air yang besar dengan kualitas air yang baik. \n\n Lokasi Wisata :\n https://goo.gl/maps/4jygFipSuHP8RDjm8 \n\n HTM :  \n 25.000/orang \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 17.00 \n\n Kontak \n 081909572048 \n\n Alternatif kontak \n  \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "baah":
        response = "Anda memilih Batu Apung Alam Hijau \n\n Deskripsi Wisata :\n Batu Apung Alam Hijau merupakan destinasi favorit yang ada di Purwakarta. Letaknya yang strategis membuat banyak pengunjung selalu ramai berdatangan terutama saat momen liburan. Batu Apung Alam Hijau itu sendiri terletak di Desa Wanasari Kecamatan Wanayasa, Purwakarta. Sebuah tempat yang sangat strategis untuk di kunjungi dan tentunya menampilkan keindahan alam sekitar. Melihat pesona kawasan Batu Apung Alam Hijau, pengunjung pasti akan betah menikmati segala fasilitas yang ditawarkan. Anda dapat mengajak anggota keluarga maupun rekan agar keseruan semakin terasa. Beragam arena wisata serta taman bermain akan siap menghilangkan segala rasa penat akibat aktivitas sehari-hari. \n\n Lokasi Wisata :\n https://goo.gl/maps/tM541hkLJNihmqfQ8 \n\n HTM :  \n Tiket Masuk Anak : Rp30.000, Dewasa : Rp40.000 ; Parkir Sepeda Motor Rp3.000 ; Parkir Mobil Rp5.000 ; Kolam Renang Rp10.000 ; Tangkap Ikan Rp10.000 ; Sewa Alat + Umpan Pemancingan Rp10.000 ; Perahu Gowes Rp15.000 \n\n Waktu Buka/Tutup : \n setiap hari jam 08.00 - 20.00 \n\n Kontak \n 087782090638 \n\n Alternatif kontak \n https://www.facebook.com/batuapungalamhijau/  \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "krpwp":
        response = "Anda memilih Kolam Renang Pusaka Water Park \n\n Deskripsi Wisata :\n Anda dapat menikmati berbagai jenis seluncuran dengan bentuk yang unik dan ukuran yang beragam. Ajak anak-anak Anda untuk menikmasi keseruan berenang di waterpark ini. Anda juga akan dikelilingi oleh pemandangan indah kota Purwakarta saat berada di sini. \n\n Lokasi Wisata :\n https://goo.gl/maps/Q3GkjeP93D7M55x6A \n\n HTM :  \n Rp. 15.000, s/d 20.000 per orang \n\n Waktu Buka/Tutup : \n setiap hari kecuali jumat jam 08.00 - 17.00 \n\n Fasilitas \n Kolamnya ada 3, gazebo, Toilet. \n\n Kontak \n12 081386761727 \n\n Alternatif kontak \n14 - \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "krbj":
        response = "Anda memilih Kolam Renang Babakan Jati \n\n Deskripsi Wisata :\n Anda dapat meikmati kolam renang disini yang sangat cocok untuk sekedar olahraga \n\n Lokasi Wisata :\n https://goo.gl/maps/5M2eQLtHD75ZofzJ8 \n\n HTM :  \n HTM 10.000/orang \n\n Waktu Buka/Tutup : \n setiap hari kecuali jumat jam 08.00 - 17.00 \n\n Kontak \n 087725139681 \n\n Alternatif kontak \n  \n\n Selamat liburan, hati-hati di jalan." 

    elif incoming_msg == "htl":
        response = "Anda memilih Hotel. Kamu ada di wilayah mana:\n1. Kecamatan Purwakarta (code : kpur) \n2. Kecamatan Wanayasa (code : kwan) \n3. Kecamatan Plered (code : kred) \n4. Kecamatan Bungursari (code : kbung) " 
    
    elif incoming_msg == "kpur":
        response = "Anda memilih Kecamatan Purwakarta. Silahkan pilih hotel:\n1. Hotel Khalsa Indah (code : hki) \n2. Urbanview Hotel Kangen Bungalow Purwakarta (code : uhkbp) \n3. Hotel Khalista (code : hkli) \n4. Hotel Grand Situ Buleud (code : hgsb) " 
    elif incoming_msg == "hki":
        response = "Anda memilih Hotel Khalsa Indah\n\n Lokasi Hotel :\n https://goo.gl/maps/FJpmxEE9XwQhiyvr5 \n\n Tiket \n https://www.tiket.com/hotel/indonesia/hotel-khalsa-indah-208001565688607511?hotelID=19bdb1aa-04fc-4577-b20f-6f7ec6a0808a&checkin=2023-08-12&checkout=2023-08-13&adult=2&country=ID&device=desktop&utm_source=google-hotel&utm_medium=hotelAds&utm_campaign=Google-Hotel-0023-B2B-none-hotel&gclid=Cj0KCQjwrMKmBhCJARIsAHuEAPQNYaHonwbR5IdMICKo82bUAFbkIyjOCIaiUCbIJ_YnY5hDvHtKPIUaAjg8EALw_wcB \n\n Traveloka \n https://www.traveloka.com/id-id/hotel/detail?spec=12-08-2023.13-08-2023.1.1.HOTEL.3000010005933.Hotel%20New%20Khalsa%20Indah.2&contexts=%7B%22accessCode%22%3A%2290975GHAD1305desktop%22%2C%22inventoryRateKey%22%3A%22povEwB3ZzsU2C6pd%2B6MdU13LUNuufACdbU0usK5vg0dM0tKsNUio4Rxug1zOzHJilcvZa8YdqqIySdppe7dolTIewZlxfjiOGz6oXLTucMvN0%2BgQ3yZPvZcoHwUFNN%2BZpcr%2F%2FNa8o9ElfN8zOYhzzZeg0X586laFpeUViPi9rxBDSkbNDj6VVy8ut0bATCXmmhLDdV0WLeT%2FFKfQ0QL8LH02Dvlx%2F8PjYogEE5yzx6g6yOKyKeIDf7jO3GM45O1o1hmSkmz3HiZNSbS8gXb3CDW9nmlhkqLKa4lLkAkZpAH0gcTfW1b8h02Mkay%2BiC4I%2BM1eg8ZkMyPXRofj%2FXgOo%2Fvnzag3zLIuKsio2qc%2FE%2BKC0I%2B4MpT6AtjonGvWhSFYeOjRTl6ytxGba%2F42pjcyydEESW7Hq%2F%2BXk7KJE212dw5LuUYVQDqxr%2B%2B3v1H4qfwwzHaEIke4gLKBu993M9y78%2FmzREQ0KgV1vvYuRfaKd1eNmO0SRV1ogUSH81Kgs05BsmVHb%2FDz2eMMIR3KhBjDXyMn1qdaM1viWqCGwU1siX1ZIegdsZIo1sjlWnbsTcjefS6Pj3RtIU6lROCEB6QAgiS1WJabPNVEO7waQAXksTDyQHUY2wqyAfRzb44KOjG0poBVHSJ1fq5iJGt%2Fs2ROyG2r1yuKaZ4GSAmh5BaCjz8%3D%22%7D&loginPromo=1&prevSearchId=1773629976605652242 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "uhkbp":
        response = "Anda memilih Urbanview Hotel Kangen Bungalow Purwakarta\n\n Lokasi Hotel :\n https://goo.gl/maps/5KtTNDWpwsWdWNDx5 \n\n Tiket\n https://www.tiket.com/hotel/indonesia/urbanview-hotel-kangen-bungalow-purwakarta-504001648805198136?hotelID=804432eb-3973-4cfa-b9fc-db9aa3598634&checkin=2023-08-12&checkout=2023-08-13&adult=2&country=ID&device=desktop&utm_source=google-hotel&utm_medium=hotelAds&utm_campaign=Google-Hotel-0023-B2B-none-hotel&gclid=Cj0KCQjwrMKmBhCJARIsAHuEAPRhZsq2G0GaKTcfYHDcXe9B5Vqx_kCHyKA4hkJRbdNy9QXpznvpi68aArZREALw_wcB \n\n Reddoorz \n https://www.reddoorz.com/id-id/hotel/indonesia/purwakarta/purwakarta/nagri-kaler/urbanview-hotel-kangen-bungalow-purwakarta?check_in_date=12-08-2023&check_out_date=13-08-2023&rooms=1&sort_by=popular&order_by=desc&currency=IDR&gha_source=true \n\n Agoda \n https://www.agoda.com/id-id/urbanview-hotel-kangen-bungalow-purwakarta/hotel/purwakarta-id.html?finalPriceView=1&isShowMobileAppPrice=false&cid=1731353&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2023-08-12&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=-1&showReviewSubmissionEntry=false&currencyCode=IDR&isFreeOccSearch=false&isCityHaveAsq=false&tspTypes=8&pushId=CgYIgJfbpgYSBgiAuuCmBhgBIIvxgg8qCioIIgIIASoCCAQ=3a9cc64a-bc78-0c02-9a0d-4ef286f3c86b_20230808_09&los=1&searchrequestid=39f3470c-a715-4a3e-b925-896f3c009328 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "hkli":
        response = "Anda memilih Hotel Khalista\n\n Lokasi Hotel :\n https://goo.gl/maps/NyRoMpxcrJhU3YwTA \n\n Tiket \n https://www.tiket.com/hotel/indonesia/hotel-khalista-206001560502048381?hotelID=abbd3ac1-7b76-4b43-958f-06e6eda2c339&checkin=2023-08-12&checkout=2023-08-13&adult=2&country=ID&device=desktop&utm_source=google-hotel&utm_medium=hotelAds&utm_campaign=Google-Hotel-0023-B2B-none-hotel&gclid=Cj0KCQjwrMKmBhCJARIsAHuEAPSkWt9FjMZS1Env0AXFepGZ2sn_IkOVO8-ct9748dHFWG8nfgqDsK4aAkFLEALw_wcB \n\n Traveloka \n https://www.traveloka.com/id-id/hotel/detail?spec=12-08-2023.13-08-2023.1.1.HOTEL.3000010005872.Hotel%20Khalista.2&contexts=%7B%22accessCode%22%3A%2290975GHAD1305desktop%22%2C%22inventoryRateKey%22%3A%22povEwB3ZzsU2C6pd%2B6MdU13LUNuufACdbU0usK5vg0dM0tKsNUio4Rxug1zOzHJilcvZa8YdqqIySdppe7dolTIewZlxfjiOGz6oXLTucMvN0%2BgQ3yZPvZcoHwUFNN%2BZpcr%2F%2FNa8o9ElfN8zOYhzzZeg0X586laFpeUViPi9rxAUGso5tAVx18vQAQDC0ml%2FmhLDdV0WLeT%2FFKfQ0QL8LH02Dvlx%2F8PjYogEE5yzx6g6yOKyKeIDf7jO3GM45O1o1hmSkmz3HiZNSbS8gXb3CDW9nmlhkqLKa4lLkAkZpAH0gcTfW1b8h02Mkay%2BiC4I%2BM1eg8ZkMyPXRofj%2FXgOo%2Fvnzag3zLIuKsio2qc%2FE%2BKC0I%2B4MpT6AtjonGvWhSFYeOjRTl6ytxGba%2F42pjcyydEESW7Hq%2F%2BXk7KJE212dw5LuUYVQDqxr%2B%2B3v1H4qfwwzHaEIke4gLKBu993M9y78%2FmzREQ0KgV1vvYuRfaKd1eNmO0SRV1ogUSH81Kgs05BsmVHb%2FDz2eMMIR3KhBjDXyMn1qdaM1viWqCGwU1siX1ZIegdsZIo1sjlWnbsTcjefS6Pj3RtIU6lROCEB6QAgiS1WJabPNVEO7waQAXksTDyQHUY2wqyAfRzb44KOjG0poBVHSJ1fq5iJGt%2Fs2ROyG2r1yuKaZ4GSAmh5BaCjz8%3D%22%7D&loginPromo=1&prevSearchId=1773630476815233263 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "hgsb":
        response = "Anda memilih Hotel Grand Situ Buleud\n\n Lokasi Hotel :\n https://goo.gl/maps/shduvw13VQgJ7WJA6 \n\n Tiket \n https://www.tiket.com/hotel/indonesia/grand-situ-buleud-112001543987086776 \n\n Traveloka \n https://www.traveloka.com/id-id/hotel/indonesia/hotel-grand-situ-buleud-3000010005866 \n\n Agoda \n https://www.agoda.com/id-id/grand-situ-buleud-hotel_3/hotel/purwakarta-id.html \n\n Selamat liburan, hati-hati di jalan." 

    elif incoming_msg == "kwan":
        response = "Anda memilih Kecamatan Wanayasa. Silahkan pilih hotel:\n1. RedDoorz Resort Syariah @ Batu Apung Purwakarta (code : rrsbap) \n2. Pesona Endah Alam Hijau Wanayasa RedPartner (code : peahwr) \n3. Porlak Jahe GTK (Giri Tirta Kahuripan) (code : pjgtk) " 
    elif incoming_msg == "rrsbap ":
        response = "Anda memilih RedDoorz Resort Syariah @ Batu Apung Purwakarta\n\n Lokasi Hotel :\n https://goo.gl/maps/n9WiSFdWbDa62fsdA \n\n Agoda \n https://www.agoda.com/id-id/reddoorz-resort-syariah-batu-apung-purwakarta/hotel/purwakarta-id.html?finalPriceView=1&isShowMobileAppPrice=false&cid=1731353&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2023-08-12&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=-1&showReviewSubmissionEntry=false&currencyCode=IDR&isFreeOccSearch=false&isCityHaveAsq=false&pushId=CgYIgJfbpgYSBgiAuuCmBhgBIN/c6gUqCioIIgIIASoCCAQ=4c80737c-919d-94ba-bd59-bc0378f913a3_20230808_09&los=1&searchrequestid=e0300b7a-4728-4a3d-a102-d4d7267647eb \n\n Reddoorz \n https://www.reddoorz.com/id-id/hotel/indonesia/purwakarta/wanayasa/wanasari/reddoorz-resort-syariah-batu-apung-purwakarta?check_in_date=12-08-2023&check_out_date=13-08-2023&rooms=1&sort_by=popular&order_by=desc&currency=IDR&gha_source=true \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "peahwr":
        response = "Anda memilih Pesona Endah Alam Hijau Wanayasa RedPartner\n\n Lokasi Hotel :\n https://goo.gl/maps/26dShsfvfkaaA7VQ6 \n\n Agoda \n https://www.agoda.com/id-id/reddoorz-resort-syariah-batu-apung-purwakarta/hotel/purwakarta-id.html?finalPriceView=1&isShowMobileAppPrice=false&cid=1731353&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2023-08-12&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=-1&showReviewSubmissionEntry=false&currencyCode=IDR&isFreeOccSearch=false&isCityHaveAsq=false&pushId=CgYIgJfbpgYSBgiAuuCmBhgBIN/c6gUqCioIIgIIASoCCAQ=4c80737c-919d-94ba-bd59-bc0378f913a3_20230808_09&los=1&searchrequestid=e0300b7a-4728-4a3d-a102-d4d7267647eb \n\n Reddoorz \n https://www.reddoorz.com/id-id/hotel/indonesia/purwakarta/wanayasa/wanayasa/pesona-endah-alam-hijau-wanayasa-redpartner?check_in_date=12-08-2023&check_out_date=13-08-2023&rooms=1&sort_by=popular&order_by=desc&currency=IDR&gha_source=true \n\n Tiket\n https://www.tiket.com/hotel/indonesia/pesona-endah-alam-hijau-wanayasa-redpartner-509001662542798408?hotelID=2ded6728-cf7f-4189-bc92-453e624d4631&checkin=2023-08-12&checkout=2023-08-13&adult=2&country=ID&device=desktop&utm_source=google-hotel&utm_medium=hotelAds&utm_campaign=Google-Hotel-0023-B2B-none-hotel&gclid=Cj0KCQjwrMKmBhCJARIsAHuEAPS3yccft7X85aUrjor_NJbz7ng6f5YpVtCQUHRSRQ06QIGhyhIzsG4aAjjkEALw_wcB \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "pjgtk":
        response = "Anda memilih Porlak Jahe GTK (Giri Tirta Kahuripan)\n\n Lokasi Hotel :\n https://goo.gl/maps/f6ZumcdS6mqqVBqR9 \n\n Traveloka \n https://www.traveloka.com/id-id/hotel/detail?spec=12-08-2023.13-08-2023.1.1.HOTEL.9000001072123.Porlak%20Jahe%20GTK%20(Giri%20Tirta%20Kahuripan).2&contexts=%7B%22accessCode%22%3A%2290975GHAD1305desktop%22%2C%22inventoryRateKey%22%3A%22povEwB3ZzsU2C6pd%2B6MdU13LUNuufACdbU0usK5vg0dM0tKsNUio4Rxug1zOzHJilcvZa8YdqqIySdppe7dolTIewZlxfjiOGz6oXLTucMvN0%2BgQ3yZPvZcoHwUFNN%2BZpcr%2F%2FNa8o9ElfN8zOYhzzZeg0X586laFpeUViPi9rxBBUTJsIMovJ%2BQMvyqIz87lmhLDdV0WLeT%2FFKfQ0QL8LH02Dvlx%2F8PjYogEE5yzx6g6yOKyKeIDf7jO3GM45O1o1hmSkmz3HiZNSbS8gXb3CDW9nmlhkqLKa4lLkAkZpAH0gcTfW1b8h02Mkay%2BiC4I%2BM1eg8ZkMyPXRofj%2FXgOo%2Fvnzag3zLIuKsio2qc%2FE%2BKC0I%2B4MpT6AtjonGvWhSFYeOjRTl6ytxGba%2F42pjcyydEESW7Hq%2F%2BXk7KJE212dw5LuUYVQDqxr%2B%2B3v1H4qfwwzHaEIke4gLKBu993M9y78%2FmzREQ0KgV1vvYuRfaKd1eNmO0SRV1ogUSH81Kgs05BsmVHb%2FDz2eMMIR3KhBjDXyMn1qdaM1viWqCGwU1siX1ZIegdsZIo1sjlWnbsTcjefS6Pj3RtIU6lROCEB6QAgiS1WJabPNVEO7waQAXksTDyQHUY2wqyAfRzb44KOjG0poBVHSJ1fq5iJGt%2Fs2ROyG2r1yuKaZ4GSAmh5BaCjz8%3D%22%7D&loginPromo=1&prevSearchId=1773630813612560234 \n\n Tiket \n https://www.tiket.com/homes/indonesia/porlak-jahe-gtk-giri-tirta-kahuripan-511001668496224141?hotelID=8bbb9c5a-54f9-43c1-b712-87373c718cde&checkin=2023-08-12&checkout=2023-08-13&adult=2&country=ID&device=desktop&utm_source=google-hotel&utm_medium=hotelAds&utm_campaign=Google-Hotel-0023-B2B-none-hotel&gclid=Cj0KCQjwrMKmBhCJARIsAHuEAPSwjg21V8igLpvTZjLjEdKNfpnyBDAAgt86IV-aPfMjoRqhLgIfwRQaAqUkEALw_wcB \n\n Selamat liburan, hati-hati di jalan." 

    elif incoming_msg == "kred":
        response = "Anda memilih Kecamatan Plered. Silahkan pilih hotel:\n1. Hidden Valley Hills (code : hvhh) \n2. RedDoorz Resort Syariah @ Jaya Tirta Abadi (code : rrsjta) \n3. The Colorville Purwakarta (code : tcp) " 
    elif incoming_msg == "hvhh":
        response = "Anda memilih Hidden Valley Hills\n\n Lokasi Hotel :\n https://goo.gl/maps/h8m4oM2GRzvXxLdx8 \n\n Agoda \n https://www.agoda.com/id-id/hidden-valley-hills/hotel/all/purwakarta-id.html?finalPriceView=1&isShowMobileAppPrice=false&cid=1731353&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2023-08-12&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=-1&showReviewSubmissionEntry=false&currencyCode=IDR&isFreeOccSearch=false&isCityHaveAsq=false&tspTypes=8&pushId=CgYIgJfbpgYSBgiAuuCmBhgBILDvpAoqCioIIgIIASoCCAQ=c255d506-693e-c9cd-c452-f188b48af835_20230808_07&los=1&searchrequestid=2bda85cd-fadd-4186-bbb5-2bc5e9175709 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "rrsjta":
        response = "Anda memilih RedDoorz Resort Syariah @ Jaya Tirta Abadi\n\n Lokasi Hotel :\n https://goo.gl/maps/6JizSFs8ZgX4CH7W6 \n\n Tiket \n https://www.tiket.com/hotel/indonesia/reddoorz-resort-syariah-jaya-tirta-abadi-210001570184122230?hotelID=e93d0013-26fb-4229-a173-948aeb032ede&checkin=2023-08-12&checkout=2023-08-13&adult=2&country=ID&device=desktop&utm_source=google-hotel&utm_medium=hotelAds&utm_campaign=Google-Hotel-0023-B2B-none-hotel&gclid=Cj0KCQjwrMKmBhCJARIsAHuEAPREcxfNd13Fi6FR0CX3SSA4thCAiX1jO-ei5_j-rX_qmAjufnVqx-gaAmufEALw_wcB \n\n Reddoorz \n https://www.reddoorz.com/id-id/hotel/indonesia/purwakarta/bojong/sukamanah/reddoorz-resort-plus-jaya-tirta-abadi?check_in_date=12-08-2023&check_out_date=13-08-2023&rooms=1&sort_by=popular&order_by=desc&currency=IDR&gha_source=true \n\n Agoda \n https://www.agoda.com/id-id/reddoorz-resort-syariah-jaya-tirta-abadi/hotel/purwakarta-id.html?finalPriceView=1&isShowMobileAppPrice=false&cid=1731353&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2023-08-12&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=-1&showReviewSubmissionEntry=false&currencyCode=IDR&isFreeOccSearch=false&isCityHaveAsq=false&tspTypes=6,8&pushId=CgYIgJfbpgYSBgiAuuCmBhgBIOO71gQqCioIIgIIASoCCAQ=e2264f91-d36d-7b29-fad5-d409856cdba2_20230808_09&los=1&searchrequestid=be67350c-faa2-4741-b2e2-d7d4d22c7177 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "tcp":
        response = "Anda memilih The Colorville Purwakarta\n\n Lokasi Hotel :\n https://goo.gl/maps/iAofqb77xKjsTr4t8 \n\n Traveloka \n https://www.traveloka.com/id-id/hotel/indonesia/the-colorville-3000020007980 \n\n Selamat liburan, hati-hati di jalan." 
    
    elif incoming_msg == "kbung":
        response = "Anda memilih Kecamatan Bungursari. Silahkan pilih hotel:\n1. Hotel Harper Purwakarta by ASTON (code : hhpa) \n2. Hotel Grand Permata (code : hgp) \n3. Prime Plaza Hotel Purwakarta (code : pphp) " 
    elif incoming_msg == "hhpa":
        response = "Anda memilih Hotel Harper Purwakarta by ASTON\n\n Lokasi Hotel :\n https://goo.gl/maps/vUP9UEzFcohnJfPw8 \n\n Agoda \n https://www.agoda.com/id-id/harper-purwakarta/hotel/purwakarta-id.html?finalPriceView=1&isShowMobileAppPrice=false&cid=1731353&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2023-08-12&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=-1&showReviewSubmissionEntry=false&currencyCode=IDR&isFreeOccSearch=false&isCityHaveAsq=false&tspTypes=8&los=1&searchrequestid=adcaec44-2060-44da-9ce7-ea51ddab330c \n\n Traveloka \n https://www.traveloka.com/id-id/hotel/detail?spec=12-08-2023.13-08-2023.1.1.HOTEL.3000010007061.Harper%20Purwakarta%20by%20ASTON.2&contexts=%7B%22accessCode%22%3A%2290975GHAD1305desktop%22%2C%22inventoryRateKey%22%3A%22povEwB3ZzsU2C6pd%2B6MdU13LUNuufACdbU0usK5vg0dM0tKsNUio4Rxug1zOzHJilcvZa8YdqqIySdppe7dolTIewZlxfjiOGz6oXLTucMvN0%2BgQ3yZPvZcoHwUFNN%2BZpcr%2F%2FNa8o9ElfN8zOYhzzZeg0X586laFpeUViPi9rxAuzBUg83cYOz0%2BwFarsJKLmhLDdV0WLeT%2FFKfQ0QL8LH02Dvlx%2F8PjYogEE5yzx6g6yOKyKeIDf7jO3GM45O1o1hmSkmz3HiZNSbS8gXb3CDW9nmlhkqLKa4lLkAkZpAH0gcTfW1b8h02Mkay%2BiC4I%2BM1eg8ZkMyPXRofj%2FXgOo%2Fvnzag3zLIuKsio2qc%2FE%2BKC0I%2B4MpT6AtjonGvWhSFYeOjRTl6ytxGba%2F42pjcyydEESW7Hq%2F%2BXk7KJE212dw5LuUYVQDqxr%2B%2B3v1H4qfwwzHaEIke4gLKBu993M9y78%2FmzREQ0KgV1vvYuRfaKd1eNmO0SRV1ogUSH81Kgs05BsmVHb%2FDz2eMMIR3KhBjDXyMn1qdaM1viWqCGwU1siX1ZIegdsZIo1sjlWnbsTcjefS6Pj3RtIU6lROCEB6QAgiS1WJabPNVEO7waQAXksTDyQHUY2wqyAfRzb44KOjG0poBVHSJ1fq5iJGt%2Fs2ROyG2r1yuKaZ4GSAmh5BaCjz8%3D%22%7D&loginPromo=1&prevSearchId=1773631431075975018 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "hgp":
        response = "Anda memilih Hotel Grand Permata\n\n Lokasi Hotel :\n https://goo.gl/maps/S4MiVjpAHFNNjPCj6 \n\n Tiket \n https://www.tiket.com/hotel/indonesia/grand-permata-purwakarta-112001543987087596?hotelID=95da7144-b124-45d2-b32d-52f43d4d7441&checkin=2023-08-12&checkout=2023-08-13&adult=2&country=ID&device=desktop&utm_source=google-hotel&utm_medium=hotelAds&utm_campaign=Google-Hotel-0023-B2B-none-hotel&gclid=Cj0KCQjwrMKmBhCJARIsAHuEAPR7j41MY_ZIbkDC3wGg9-JCARiqur-unQDl4UfPM429NADbAwqot1YaAn-YEALw_wcB \n\n Traveloka \n https://www.traveloka.com/id-id/hotel/detail?spec=12-08-2023.13-08-2023.1.1.HOTEL.3000010006039.Hotel%20Grand%20Permata%20Purwakarta.2&contexts=%7B%22accessCode%22%3A%2290975GHAD1305desktop%22%2C%22inventoryRateKey%22%3A%22povEwB3ZzsU2C6pd%2B6MdU13LUNuufACdbU0usK5vg0dM0tKsNUio4Rxug1zOzHJilcvZa8YdqqIySdppe7dolTIewZlxfjiOGz6oXLTucMvN0%2BgQ3yZPvZcoHwUFNN%2BZpcr%2F%2FNa8o9ElfN8zOYhzzZeg0X586laFpeUViPi9rxBy%2BEjTkFgeB5nUUPQ0aqEFmhLDdV0WLeT%2FFKfQ0QL8LH02Dvlx%2F8PjYogEE5yzx6g6yOKyKeIDf7jO3GM45O1o1hmSkmz3HiZNSbS8gXb3CDW9nmlhkqLKa4lLkAkZpAH0gcTfW1b8h02Mkay%2BiC4I%2BM1eg8ZkMyPXRofj%2FXgOo%2Fvnzag3zLIuKsio2qc%2FE%2BKC0I%2B4MpT6AtjonGvWhSFYeOjRTl6ytxGba%2F42pjcyydEESW7Hq%2F%2BXk7KJE212dw5LuUYVQDqxr%2B%2B3v1H4qfwwzHaEIke4gLKBu993M9y78%2FmzREQ0KgV1vvYuRfaKd1eNmO0SRV1ogUSH81Kgs05BsmVHb%2FDz2eMMIR3KhBjDXyMn1qdaM1viWqCGwU1siX1ZIegdsZIo1sjlWnbsTcjefS6Pj3RtIU6lROCEB6QAgiS1WJabPNVEO7waQAXksTDyQHUY2wqyAfRzb44KOjG0poBVHSJ1fq5iJGt%2Fs2ROyG2r1yuKaZ4GSAmh5BaCjz8%3D%22%7D&loginPromo=1&prevSearchId=1773631505574163730 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "pphp":
        response = "Anda memilih Prime Plaza Hotel Purwakarta\n\n Lokasi Hotel :\n https://goo.gl/maps/7q8r8ysZPeM5pSp7A \n\n Traveloka \n https://www.traveloka.com/id-id/hotel/detail?spec=12-08-2023.13-08-2023.1.1.HOTEL.3000010001102.Prime%20Plaza%20Hotel%20Purwakarta.2&contexts=%7B%22accessCode%22%3A%2290975GHAD1305desktop%22%2C%22inventoryRateKey%22%3A%22povEwB3ZzsU2C6pd%2B6MdUxPQfH0zjQrhnrQN8muKP1lM0tKsNUio4Rxug1zOzHJilcvZa8YdqqIySdppe7dolTIewZlxfjiOGz6oXLTucMvN0%2BgQ3yZPvZcoHwUFNN%2BZpcr%2F%2FNa8o9ElfN8zOYhzzZeg0X586laFpeUViPi9rxCwQtGhQ6NG%2FvJNUErRtS1bmhLDdV0WLeT%2FFKfQ0QL8LH02Dvlx%2F8PjYogEE5yzx6g6yOKyKeIDf7jO3GM45O1o1hmSkmz3HiZNSbS8gXb3CDW9nmlhkqLKa4lLkAkZpAH0gcTfW1b8h02Mkay%2BiC4I%2BM1eg8ZkMyPXRofj%2FXgOo%2Fvnzag3zLIuKsio2qc%2FE%2BKC0I%2B4MpT6AtjonGvWhSFYeOjRTl6ytxGba%2F42pjcyydEESW7Hq%2F%2BXk7KJE212dw5LuUYVQDqxr%2B%2B3v1H4qfwwzHaEIke4gLKBu993M9y78%2FmzREQ0KgV1vvYuRfaKd1eNmO0SRV1ogUSH81Kgs05BsmVHb%2FDz2eMMIR3KhBjDXyMn1qdaM1viWqCGwU1siX1ZIegdsZIo1sjlWnbsTcjefS6Pj3RtIU6lROCEB6QAgiS1WJabPNVEO7waQAXksTDyQHUY2wqyAfRzb44KOjG0poBVHSJ1fq5iJGt%2Fs2ROyG2r1yuKaZ4GSAmh5BaCjz8%3D%22%7D&loginPromo=1&prevSearchId=1773631582002770159 \n\n Agoda \n https://www.agoda.com/id-id/prime-plaza-hotel-purwakarta_2/hotel/purwakarta-id.html?finalPriceView=1&isShowMobileAppPrice=false&cid=1731353&numberOfBedrooms=&familyMode=false&adults=2&children=0&rooms=1&maxRooms=0&checkIn=2023-08-12&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=-1&showReviewSubmissionEntry=false&currencyCode=IDR&isFreeOccSearch=false&isCityHaveAsq=false&tspTypes=4,8&pushId=CgYIgJfbpgYSBgiAuuCmBhgBIPq/DyoKKggiAggBKgIIBA==2077e78f-62ca-3a3b-e7f4-62d3c7049edf_20230808_09&los=1&searchrequestid=147650d9-5f10-45fe-9717-e901b8ea26f8 \n\n Selamat liburan, hati-hati di jalan." 

    elif incoming_msg == "ook":
        response = "Anda memilih Oleh-Oleh Khas. Silakan pilih opsi berikutnya:\n1. Galeri Menong (code : gmo)  \n2. Pusat Oleh-Oleh Purwakarta Simping 49 (code : pops) \n3. Priangan Family (code : pfo) \n4. Pusat Oleh-Oleh dan Manisan Manah Rasa(code : podmr) \n5. Sate Maranggi Haji Yetty(code : smhy) \n6. Sate Maranggi Bah Use (code : smbu) " 
    elif incoming_msg == "gmo":
        response = "Anda memilih Galeri Menong\n\n Lokasi Toko :\n https://goo.gl/maps/87chNyNMHoMEKfVB8 \n\n Kontak \n 087725139681 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "pops":
        response = "Anda memilih Pusat Oleh-Oleh Purwakarta Simping 49\n\n Lokasi Toko :\n https://goo.gl/maps/tnyN9JrWEZNARsDZA \n\n Kontak \n 087879991990 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "pfo":
        response = "Anda memilih Priangan Family 3\n\n Lokasi Toko :\n https://goo.gl/maps/fZnjqqc3vYq68c3h9 \n\n Kontak \n 081383334470 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "podmr":
        response = "Anda memilih Pusat Oleh-Oleh dan Manisan Manah Rasa\n\n Lokasi Toko :\n https://goo.gl/maps/SAARoXEPBc36Z8ba6 \n\n Kontak \n 087779751296 \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "smhy":
        response = "Anda memilih Sate Maranggi Haji Yetty\n\n Lokasi Toko :\n https://goo.gl/maps/WfdhuwvAfsL7UxGL6 \n\n Kontak \n 0264351077 \n\n Kontak Alternatif \n https://www.instagram.com/satemaranggihajiyettycibungur/?hl=id \n\n Selamat liburan, hati-hati di jalan." 
    elif incoming_msg == "smbu":
        response = "Anda memilih Sate Maranggi Bah Use\n\n Lokasi Toko :\n https://goo.gl/maps/GXwE1qzeM1pGoNnq8 \n\n Kontak \n 082115322899 \n\n Selamat liburan, hati-hati di jalan." 
    
    else:
        response = "Maaf, kata kunci yang anda masukkan kurang tepat\n\nSilahkan ketik *Halo* untuk kembali ke menu awal"


    resp = MessagingResponse()
    resp.message(response)
    return str(resp)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))
